---
# tasks file for nginx-role
- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Configure hostname
  hostname:
    name: "ansiblemaster"

- name: Create Nginx configuration file
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify: Restart nginx

- name: Ensure Nginx is running
  service:
    name: nginx
    state: restarted
    enabled: yes

- name: Schedule a cron job to deploy the HTML page at 8:30 AM
  cron:
    name: "Deploy HTML page"
    minute: "30"
    hour: "8"
    job: "ansible-playbook /path/to/your/playbook.yml"
