--- 
- name: Create new tomcat group
  group:
    name:  tomcat
    state: present

- name:  Create tomcat user 
  user:
    name: tomcat
    groups: tomcat
    shell: /bin/false 
    home: /opt/tomcat
    state: present 
#- name: Ensure /opt/tomcat/webapps directory exists
#  file:
#    path: /opt/tomcat/webapps
#    state: directory
#    owner: tomcat
#    group: tomcat
#    mode: '0755'
