---
- hosts: javaserver
  become: yes
  vars:
     myvar_1 : git
     myvar_2 : tree
     myvar_3 : apache2
  tasks:
    - name : i want display my var
      debug: 
        msg: "{{ myvar_2}}"
    - name : i want to install java jdk 8 on ubuntu
      apt :
        name: "{{ item }}"
        state: present
    - name : i want to install java jdk 8 on ubuntu
      yum :
        name: "{{ item }}"
        state: present
      loop:  
        - "{{ myvar_1 }}"
        - "{{ myvar_2 }}"
        - "{{ myvar_3}}"

   - name: Install packages using command
     command: apt-get install -y "{{ item }}"
     loop:
    - "{{ myvar_1 }}"
    - "{{ myvar_2 }}"
    - "{{ myvar_3 }}"
