---
- hosts: javaserver
  become: yes
  vars:
     myvar_1 : git
     myvar_2 : tree
     myvar_3 : apache2
  tasks:
    - name : i want display my var
      debug: 
        msg: "{{myvar_1}}"
    - name : i want to install java jdk 8 on ubuntu
      apt :
        name: "{{item}}"
        state: present
        loop:
            -
          - "{{myvar_1}}"
          - "{{myvar_2}}"
          - "{{myvar_3}}"
            