---
- hosts: all
  become: yes
  tasks:
   - name: Install JDK 8 on ubuntu
     apt:
       name: openjdk-8-jdk
       state: present
     when: ansible_os_family == "Debian"

   - name: Install JDK 8 on Red Hat
     yum:
       name: java-1.8.0-openjdk-devel
       state: present
     when: ansible_os_family == "RedHat"

