---
- name: Create a file with date and 'satish'
  copy:
    content: "{{ ansible_date_time.date }} satish"
    dest: /var/www/html/satish
    owner: ec2-user
    group: ec2-user
    mode: '0644'

- name: Install Apache web server
  package:
    name: httpd
    state: present

- name: Start and enable Apache
  service:
    name: httpd
    state: started
    enabled: true
